### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by LapTran04** [wem2017/flutter_bloc_boilerplate#1]
Hi, I'm configuring a new boilerplate and I want to use this but It has some errors when running.
This is errors when running on iOS simulator.
![Screen Shot 2022-08-17 at 14 36 13](https://user-images.githubusercontent.com/111327790/185061685-667ce800-a008-41e6-86da-0c600cd1be47.png)

**Comment by nguyenthanhphap1413** [comment]
Did you try to clean and re-pub get before?
